=== DanielMSchmidt/skript-xml/uebung/S1/a.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:exam="http://www.exam.org/xml/exam"
        targetNamespace="http://www.exams.org"
        elementFormDefault="qualified">





  <xsd:element name="exam">
     <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="students">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="student" minOccurs="0" maxOccurs="50">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="firstname" type="xsd:string" />
                    <xsd:element name="lastname" type="xsd:string" />
                    <xsd:element name="email">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                           <xsd:pattern value="[^@]+@[^\.]+\..+"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="career">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:enumeration value="bachelor" />
                          <xsd:enumeration value="Diploma" />
                          <xsd:enumeration value="ph.d." />
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                  <xsd:attribute name="mat" type="xsd:ID" ></xsd:attribute>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="test">
          <xsd:complexType>
            <xsd:element name="results">
              <xsd:attribute name="subject" type="xsd:string" />
              <xsd:attribute name="date" type="date" />
              <xsd:attribute name="startingTime" type="time" />
              <xsd:attribute name="duration" type="integer" />
              <xsd:attribute name="unit" type="xsd:string" />
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="result" type="xsd:string">
                    <xsd:complexType>
                      <xsd:attribute name="mat" type="integer" />
                    </xsd:complexType>
                  </xsd:element>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== DanielMSchmidt/skript-xml/uebung/S1/b.xml
<?xml version="1.0" encoding="utf-8"?>
<exam xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="a.xsd">
    <students>
        <student id="1" mat="123456">
            <firstname>Peter</firstname>
            <lastname>Lustig</lastname>
            <email>peter@lustig.de</email>
            <career>bachelor</career>
        </student>
    </students>
    <test subject="XML in Communication Systems" date="12.12.2012" startingTime="14:00" duration="1" unit="hour">
        <results>
            <result mat="123456">1.0</result>
        </results>
    </test>
</exam>
